default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    # 1. certificates, provisioning_profile 가져오기
    app_store_connect_api_key(
        key_id: ENV["API_KEY_ID"],
        issuer_id: ENV["API_ISSUER_ID"],
        key_content: ENV["API_PRIVATE_KEY"]
    )
    # 2. build_number 증가
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )

    # 3.build app
    build_app(
      configuration: "Debug"
    )

    pilot
  end
end