name: Deploy iOS and Android App to App Store and Play Store
on:
  push:
    tags:
      - 'v*'
  jobs:
    beta-ios:
      name: Build and release iOS app
      runs-on: macos-latest
      steps:
        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: latest-stable
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2.8.0
          with:
            flutter-version: '3.10.6'
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.1.2'
        - name: Install Fastlane
          run: cd ios && bundle install && cd ..
        - name: Install packages
          run: flutter pub get
        - name: Install pods
          run: cd ios && pod install && cd ..
        - name: Prebuild
          run: flutter build ios --release --no-codesign
        - name: Execute Fastlane command
          run: cd ios && fastlane testflight
          timeout-minutes: 40